import { CarBodyType } from "../../../api/truck/CarBodyType";

export const CARBODY_DISPLAY_NAME_MAP = new Map<Object, string>([
    [ CarBodyType.tentTruck, "Тентованный" ],
    [ CarBodyType.container, "Контейнер" ],
    [ CarBodyType.van, "Фугон" ],
    [ CarBodyType.allMetal, "Цельнометалл" ],
    [ CarBodyType.isothermal, "Изотермический" ],
    [ CarBodyType.refrigerator, "Рефрижератор" ],
    [ CarBodyType.refrigeratorMult, "Реф. мультирежимный" ],
    [ CarBodyType.bulkheadRefr, "Реф. с перегородкой" ],
    [ CarBodyType.meatRailsRef, "Реф.-тушевоз" ],
    [ CarBodyType.flatbed, "Бортовой" ],
    [ CarBodyType.opentop, "Открытый конт." ],
    [ CarBodyType.opentrailer, "Площадка без бортов" ],
    [ CarBodyType.dumpTruck, "Самосвал" ],
    [ CarBodyType.barge, "Шаланда" ],
    [ CarBodyType.dolly, "Низкорамный" ],
    [ CarBodyType.dollyPlat, "Низкорам.платф." ],
    [ CarBodyType.adjustable, "Телескопический" ],
    [ CarBodyType.tral, "Трал" ],
    [ CarBodyType.beamTruckNgb, "Балковоз(негабарит)" ],
    [ CarBodyType.bus, "Автобус" ],
    [ CarBodyType.Autocart, "Автовоз" ],
    [ CarBodyType.autotower, "Автовышка" ],
    [ CarBodyType.autoCarrier, "Автотранспортер" ],
    [ CarBodyType.сoncreteTruck, "Бетоновоз" ],
    [ CarBodyType.bitumenTruck, "Битумовоз" ],
    [ CarBodyType.fuelTank, "Бензовоз" ],
    [ CarBodyType.offRoader, "Вездеход" ],
    [ CarBodyType.gas, "Газовоз" ],
    [ CarBodyType.grainTruck, "Зерновоз" ],
    [ CarBodyType.horseTruck, "Коневоз" ],
    [ CarBodyType.containerTrail, "Контейнеровоз" ],
    [ CarBodyType.furageTuck, "Кормовоз" ],
    [ CarBodyType.crane, "Кран" ],
    [ CarBodyType.timberTruck, "Лесовоз" ],
    [ CarBodyType.scrapTruck, "Ломовоз" ],
    [ CarBodyType.manipulator, "Манипулятор" ],
    [ CarBodyType.microbus, "Микроавтобус" ],
    [ CarBodyType.flourTruck, "Муковоз" ],
    [ CarBodyType.panelsTruck, "Панелевоз" ],
    [ CarBodyType.pickup, "Пикап" ],
    [ CarBodyType.ripetruck, "Пухтовоз" ],
    [ CarBodyType.pyramid, "Пирамида" ],
    [ CarBodyType.rollTruck, "Рулоновоз" ],
    [ CarBodyType.tractor, "Седельный тягач" ],
    [ CarBodyType.cattle, "Скотовоз" ],
    [ CarBodyType.innloader, "Стекловоз" ],
    [ CarBodyType.pipeTruck, "Трубовоз" ],
    [ CarBodyType.cementTruck, "Цементовоз" ],
    [ CarBodyType.tankerTruck, "Автоцистерна" ],
    [ CarBodyType.chipTruck, "Щеповоз" ],
    [ CarBodyType.wrecker, "Эвакуатор" ],
    [ CarBodyType.dualPurpose, "Грузопассажирский" ],
    [ CarBodyType.klyushkovoz, "Клюшковоз" ],
    [ CarBodyType.garbageTruck, "Мусоровоз" ],
    [ CarBodyType.jumbo, "Jumbo" ],
    [ CarBodyType.tankContainer20, "20' танк-контейнер" ],
    [ CarBodyType.tankContainer40, "40' танк-контейнер" ],
    [ CarBodyType.mega, "Мега фура" ],
    [ CarBodyType.doppelstock, "Допельшток" ],
    [ CarBodyType.slidingSemiTrailer2040, "Раздвижной полуприцеп 20'/40'" ],
])

export const CARBODY_DISPLAY_NAME_ARRAY = Array.from(CARBODY_DISPLAY_NAME_MAP, ([value, displayName]) => ({ value, displayName }));
